### ISSUE TITLE
Polygonen van CBS Buurten

### ISSUE THREAD

**Issue by MarinusVonhof** [PDOK/data.labs.pdok.nl#7]
Openstaande vraag: CBS Buurten dekken niet alle bebouwing af? Een wijk hoeft geen buurt te bevatten? En, dekken wijken wel alle bebouwing af?

**Comment by reinvantveer** [comment]
Volgens mij is het een landsdekkende dataset. Je kan de WFS bekijken, links beschikbaar via: http://nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/dcb7f0d7-d70b-4eab-9a46-7af98de860bd

**Comment by reinvantveer** [comment]
Kunnen we dit issue sluiten?

**Comment by MarinusVonhof** [comment]
Prima Rein, in de data-story nog wel analyseren waarom we geen CBS-buurt overlappend met rioleringsgebied Pancras kunnen vinden
